// MUTATIONS
const SET_USER = 'SET_USER'

const SET_USERS = 'SET_USERS'
const SET_SINGLE_USER = 'SET_SINGLE_USER'
const REMOVE_USER = 'REMOVE_USER'

const SET_FILTER_USERS = 'SET_FILTER_USERS'
const SET_CONCAT_FILTER_USERS = 'SET_CONCAT_FILTER_USERS'

const SET_REMOVED_USERS = 'SET_REMOVED_USERS'
const REMOVE_REMOVED_USER = 'REMOVE_REMOVED_USER'

const SET_DONE_USERS = 'SET_DONE_USERS'
const REMOVE_DONE_USER = 'REMOVE_DONE_USER'

const SET_IS_INIT = 'SET_IS_INIT'

const SET_TERM_SEARCH = 'SET_TERM_SEARCH'

// ROTAS
const TODOS = 'todos'
const LIXEIRA = 'lixeira'
const ATENDIDOS = 'atendidos'

export default {
  SET_USER,

  SET_USERS,
  SET_SINGLE_USER,
  REMOVE_USER,

  SET_FILTER_USERS,
  SET_CONCAT_FILTER_USERS,

  SET_REMOVED_USERS,
  REMOVE_REMOVED_USER,

  SET_DONE_USERS,
  REMOVE_DONE_USER,

  SET_IS_INIT,

  SET_TERM_SEARCH,

  TODOS,
  LIXEIRA,
  ATENDIDOS
}
